language: objective-c
osx_image: xcode7.2

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- pod install --project-directory=TokenRow/Example
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xctool clean build -workspace TokenRow/Example/Example.xcworkspace -scheme Example -sdk iphonesimulator
- set -o pipefail && xcodebuild test -workspace TokenRow/Example/Example.xcworkspace -scheme Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
