language: objective-c
osx_image: xcode8
env:
  - DESTINATION="OS=10.0,name=iPhone 6s" SCHEME="Example" SDK=iphonesimulator10.0

before_install:
- pod install --project-directory=TokenRow/Example
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -workspace TokenRow/Example/Example.xcworkspace -scheme "$SCHEME" -sdk "$SDK"
- xcodebuild test -workspace TokenRow/Example/Example.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty -c
